### ISSUE TITLE
Erro ao rodar comando com *

### ISSUE THREAD

**Issue by henriquek3** [TiagoSilvaPereira/vemto-commands-plugin#1]
![image](https://user-images.githubusercontent.com/17914565/203140976-75112d72-21ae-441e-b167-8d3825885bf2.png)

**Comment by TiagoSilvaPereira** [comment]
@henriquek3 o Vemto bloqueia comandos com "*" pois eles podem ser potencialmente perigosos, então plugins não possuem essa permissão... nesse caso o ideal é criar um script PHP (ou qualquer outra linguagem) que roda o comando e chamá-lo, ao invés de rodar o comando diretamente
